### ISSUE TITLE
Clarify what is meant by 'lightweight'

### ISSUE THREAD

**Issue by jkachmar** [kowainik/prolens#41]
[As u/arybczak mentions on r/haskell](https://www.reddit.com/r/haskell/comments/jawyaj/announcement_prolens_lightweight_profunctor_optics/g8slqyg/?context=3), it's not entirely clear what the README is supposed to mean when it says that `prolens` is a "lightweight" optics library in comparison to `optics`.

I'm assuming that this is supposed to be "conceptually lightweight", since `prolens` seems to be billed as an educational library, but I figured it would be worth opening an issue to clarify.

Thanks!

**Comment by chshersh** [comment]
Hi @jkachmar! The [Features](https://github.com/kowainik/prolens#features) section gives an explanation of what we mean by saying "lightweight":

![Screenshot from 2020-10-14 18-12-09](https://user-images.githubusercontent.com/4276606/96022512-e35eb100-0e48-11eb-8b73-61b5777b4137.png)
